files:
  - source: /**/values/strings.xml
    translation: /**/values-%android_code%/strings.xml
    translate_attributes: '0'
    content_segmentation: '0'
  - source: /.github/ISSUE_TEMPLATE/bug_report.md
    translation: /.github/ISSUE_TEMPLATE/bug_report_%android_code%.md
  - source: /.github/ISSUE_TEMPLATE/feature_request.md
    translation: /.github/ISSUE_TEMPLATE/feature_request_%android_code%.md
